Repository kORzix/KiddieEd-react-frontend, pull requests merged in 2023-09, with the labels that each got.

#36 30 photo isnt upload database
  .gitignore
  src/App.js
  src/components/Card.js
  src/configs/index.js
  src/images/upload.jpg
  src/index.css
  src/pages/LessonPlans.js
  src/pages/lesson/AddLesson.js
  src/pages/lesson/EditCourse.js
  src/pages/lesson/EditLesson.js
  src/pages/lesson/Photo.js
  src/pages/lesson/Prev.js
  src/pages/lesson/ViewAll.js
  src/pages/lesson/ViewLesson.js
  src/pages/lesson/ViewLessons.js
Labels: documentation

#37 30 photo isnt upload database
  src/App.js
  src/components/Card.js
  src/configs/index.js
  src/index.css
  src/pages/LessonPlans.js
  src/pages/lesson/AddLesson.js
  src/pages/lesson/EditCourse.k.js
  src/pages/lesson/EditLesson.js
  src/pages/lesson/ViewAll.js
  src/pages/lesson/ViewLesson.js
  src/pages/lesson/ViewLessons.js
Labels: feat

#44 Lesson plan dynamic
  package-lock.json
  public/index.html
  src/App.js
  src/pages/LessonPlans.js
  src/pages/games/AddGame.js
  src/pages/games/EditGame.js
  src/pages/games/ViewGame.js
  src/pages/games/ViewGames.js
  src/pages/lesson-plans/AddPlan.js
  src/pages/lesson-plans/EditPlan.js
  src/pages/lesson-plans/ViewPlan.js
  src/pages/lesson-plans/ViewPlans.js
Labels: feat

#45 worksheet dynamic
  src/App.js
  src/pages/LessonPlans.js
  src/pages/Worksheets.js
  src/pages/worksheets/AddSheet.js
  src/pages/worksheets/EditSheet.js
  src/pages/worksheets/ViewSheet.js
  src/pages/worksheets/ViewSheets.js
Labels: enhancement

#46 set icons
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  src/components/Card.js
  src/pages/LessonPlans.js
  src/pages/More.js
  src/pages/Worksheets.js
Labels: documentation, feat

#52 bubble effect
  src/App.js
  src/components/Eff.css
  src/components/Eff.js
Labels: feat

#54 Chatbot
  src/App.js
  src/components/chatbot.js
  src/index.css
Labels: enhancement

#56 Card
  src/pages/Games.js
  src/pages/GuidedLessons.js
  src/pages/Home.js
  src/pages/More.js
  src/pages/Worksheets.js
Labels: enhancement

#58 Import card
  src/pages/Games.js
  src/pages/GuidedLessons.js
  src/pages/Home.js
  src/pages/More.js
  src/pages/Worksheets.js
Labels: enhancement

#57 API
  package-lock.json
  package.json
  src/components/chatbot.js
  src/config.js
Labels: documentation

#59 card and api
  package-lock.json
  package.json
  src/components/chatbot.js
  src/config.js
Labels: enhancement

#73 Err/card
  src/App.js
  src/components/Card.js
  src/pages/Games.js
  src/pages/GuidedLessons.js
  src/pages/Home.js
  src/pages/LessonPlans.js
  src/pages/More.js
  src/pages/Worksheets.js
  src/pages/games/AddGame.js
  src/pages/guided-lessons/ViewGuideds.js
Labels: fix

#74 dev/err
  src/components/chatbot.js
  src/pages/GuidedLessons.js
  src/pages/More.js
Labels: fix

#76 Admin
  package-lock.json
  package.json
  src/App.js
  src/components/assist.js
  src/images/Games_D.png
  src/images/Guidedlessons_D.png
  src/images/LessonPlans_D.png
  src/images/plans_D.png
  src/images/users_D.png
  src/images/worksheet_D.png
  src/index.js
  src/pages/Games.js
  src/pages/GuidedLessons.js
  src/pages/Home.js
  src/pages/adminDashboard.js
Labels: fix

#81 fixed chatbot
  src/components/chatBot.js
  src/components/topnavbar.js
  src/index.css
  src/pages/adminDashboard.js
Labels: fix

#82 Nav edit
  src/components/topnavbar.js
  src/configs/index.js
Labels: enhancement

#86 Assist
  package-lock.json
  package.json
  src/App.js
  src/components/assist.js
  src/configs/index.js
Labels: fix

#88 Update assistant
  src/components/assist.js
  src/index.css
Labels: fix

#89 add navigate locations
  src/App.js
  src/components/assist.js
Labels: fix

#94 Card style
  src/components/navbar.js
  src/pages/Home.js
  src/pages/games/ViewGame.js
  src/pages/guided-lessons/ViewGuided.js
  src/pages/lesson-plans/ViewPlan.js
  src/pages/worksheets/ViewSheet.js
Labels: enhancement

#95 profile route update
  src/pages/More.js
Labels: enhancement

#104 Login
  .dockerignore
  Dockerfile
  src/components/navbar.js
  src/index.css
  src/pages/Home.js
  src/pages/LoginPage.js
  src/pages/Register.js
Labels: fix

#105 Dev
  src/components/navbar.js
  src/index.css
  src/pages/Home.js
  src/pages/LoginPage.js
  src/pages/Register.js
Labels: fix

#108 Navbar LOGO png added
  src/components/navbar.js
  src/images/kiddieed_logo.png
Labels: enhancement
