Repository kORzix/KiddieEd-react-frontend, pull requests merged in 2023-08, with the labels that each got.

#6 All pages are made responsive
  src/App.js
  src/pages/Games.js
  src/pages/GuidedLessons.js
  src/pages/LessonPlans.js
  src/pages/More.js
  src/pages/Worksheets.js
Labels: documentation

#8 Did some profile changes
  src/index.css
  src/pages/More/Profile.js
Labels: documentation

#10 Add search button
  src/components/navbar.js
  src/index.css
Labels: enhancement

#9 merge confict
  src/App.js
  src/components/Images/star_checked.png
  src/components/Images/star_unchecked.png
  src/components/card1.css
  src/components/card1.js
  src/index.js
Labels: invalid

#13 Search button done & nav hide fixed
  src/App.js
  src/NotFound.js
  src/components/card1.css
  src/components/card1.js
  src/components/navbar.js
  src/images/404.jpg
  src/index.css
Labels: enhancement

#14 routes
  src/App.js
  src/components/test1.js
  src/index.js
  src/pages/Home.js
Labels: bug

#15 TopNavBar
  src/App.js
  src/components/test1.js
  src/components/topnavbar.js
  src/pages/Games.js
  src/pages/Home.js
Labels: enhancement

#16 TopNavBar component added to all pages
  src/App.js
  src/components/topnavbar.js
  src/pages/Games.js
  src/pages/GuidedLessons.js
  src/pages/Home.js
  src/pages/LessonPlans.js
  src/pages/More.js
  src/pages/Worksheets.js
Labels: enhancement

#21 Nav images separated
  src/App.js
  src/components/navBarImg.js
  src/components/topnavbar.js
Labels: enhancement

#22 Set profile route
  src/App.js
Labels: documentation

#25 add lessons save
  package-lock.json
  package.json
  src/App.js
  src/pages/More/Profile.js
  src/pages/admin/AddCourse.js
Labels: documentation

#26 lessons cru done
  src/App.js
  src/pages/lesson/AddCourse.js
  src/pages/lesson/EditCourse.js
  src/pages/lesson/ViewAll.js
  src/pages/lesson/ViewCourse.js
Labels: documentation

#27 add serch and delete oprations
  src/pages/lesson/ViewAll.js
Labels: enhancement

#28 Crud all done
  public/index.html
  src/App.js
  src/index.css
  src/pages/lesson/AddCourse.js
  src/pages/lesson/Photo.js
  src/pages/lesson/Prev.js
  src/pages/lesson/ViewAll.js
Labels: bug

#35 edit photo done
  src/images/upload.jpg
  src/pages/lesson/AddCourse.js
  src/pages/lesson/EditCourse.js
  src/pages/lesson/EditCourse.k.js
  src/pages/lesson/ViewAll.js
Labels: fix
